### ISSUE TITLE
Remove border 

### ISSUE THREAD

**Issue by amilajack** [mcchrish/hyperterm-gruvbox-dark#2]
<img width="546" alt="screen shot 2016-11-18 at 9 42 53 am" src="https://cloud.githubusercontent.com/assets/6374832/20440131/8ac87736-ad73-11e6-9f2d-2d833fe1de71.png">

What do you think about removing the border in the top left?

**Comment by mcchrish** [comment]
The contrast might be too low for some people to easily recognize the active tab. I think people chose gruvbox because of its good enough contrast and bright colors 🌈 .

Is there a way for plugins to make it _toggleable_ in their hyper config file? I haven't been keeping up with hyper lately. That way, everybody's happy.

**Comment by amilajack** [comment]
How about something like this?

<img width="694" alt="screen shot 2016-11-18 at 3 21 53 pm" src="https://cloud.githubusercontent.com/assets/6374832/20450122/c52f140a-ada2-11e6-8506-cf4fff279e4d.png">

**Comment by mcchrish** [comment]
Oh, that looks better.
A PR is welcome 👍

**Comment by dmnd** [comment]
@amilajack please send that PR, your screenshot looks really good.

**Comment by amilajack** [comment]
I don't have experience with editing hyper themes
